version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres_db
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi_app:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "7860:7860"
    environment:
      - PORT=7860
    volumes:
      - ./fastapi:/app
      - huggingface_cache:/home/user/.cache/huggingface
    restart: always
    depends_on:
      - db

volumes:
  postgres_data:
  huggingface_cache:
