spring.application.name=InstaCv
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d05u0lidbo4c73927d20-a.oregon-postgres.render.com:5432/instacv_db
spring.datasource.username=instacv_admin
spring.datasource.password=zdcekb2JUC8zAOYcylkAxo3OoWbEozub



#JPA Configuration
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true


#JWT Configuration
jwt.secret=LpUVZ/3XBxQEdJodrAKFYPc68QTwQOx6odvXDk0UU1Y=
jwt.expiration=86400000

#Gateways Client Configuration
job.skill.extraction.url=http://localhost:8000
skill.matching.url=http://localhost:8001


# GitHub OAuth Configuration
github.client.id=Ov23liKyMiHZx5rl0FoN
github.client.secret=213246ac4f9391fe847604ef76e0b4334c309ecd
github.callback.url=http://localhost:8080/api/github/test/callback