#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
#Gateways Client Configuration
job.skill.extraction.url=https://youssefmorad1-instacv-gp.hf.space/skills
skill.matching.url=https://youssefmorad1-instacv-gp.hf.space/similarity
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=instacvresume@gmail.com
spring.mail.password=ldeyqubzdobncism
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Frontend Configuration
frontend.reset-url=http://localhost:5173/set-password
frontend.oauth2-success-url=http://localhost:5173/oauth2-success
# GitHub OAuth Configuration
github.client.id=Ov23liKyMiHZx5rl0FoN
github.client.secret=213246ac4f9391fe847604ef76e0b4334c309ecd
github.callback.url=http://localhost:8080/api/github/test/callback
#Google configurations
spring.security.oauth2.client.registration.google.client-id=580949131603-cla37m9o0vl1175ipfeogngh2j0p4076.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid, profile, email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/api/auth/oauth2/code/google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email