spring.application.name=InstaCv
server.port=8080
#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=123
#JPA Configuration
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
#JWT Configuration
jwt.secret=LpUVZ/3XBxQEdJodrAKFYPc68QTwQOx6odvXDk0UU1Y=
jwt.expiration=86400000
#Gateways Client Configuration
job.skill.extraction.url=http://localhost:8000
skill.matching.url=http://localhost:8001


# GitHub OAuth Configuration
github.client.id=Ov23liKyMiHZx5rl0FoN
github.client.secret=213246ac4f9391fe847604ef76e0b4334c309ecd
github.callback.url=http://localhost:8080/api/github/test/callback


# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=instacvresume@gmail.com
spring.mail.password=ldeyqubzdobncism
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true